export interface Animation {
  name: string;
  value: string;
}

export const ENTRANCES_ANIMATIONS: Animation[] = [
  { name: 'Scale In Top', value: 'scale_in_top' },
  { name: 'Scale In Horizontal Center', value: 'scale_in_hor_center' },
  { name: 'Scale In Vertical Center', value: 'scale_in_ver_center' },
  { name: 'Rotate', value: 'rotate_animation' },
  { name: 'Swirl Forward', value: 'swirl_fwd' },
  { name: 'Swirl Back', value: 'swirl_back' },
  { name: 'Flip In', value: 'flip_in' },
  { name: 'Slit In Vertical', value: 'slit_in_ver' },
  { name: 'Slit In Horizontal', value: 'slit_in_hor' },
  { name: 'Slide In Top', value: 'slide_in_top' },
  { name: 'Slide In Bottom', value: 'slide_in_bottom' },
  { name: 'Slide In Right', value: 'slide_in_right' },
  { name: 'Slide In Left', value: 'slide_in_left' },
  { name: 'Slide In Blurred Top', value: 'slide_in_blurred_top' },
  { name: 'Slide In Blurred Bottom', value: 'slide_in_blurred_bottom' },
  { name: 'Slide In Blurred Right', value: 'slide_in_blurred_right' },
  { name: 'Slide In Blurred Left', value: 'slide_in_blurred_left' },
  { name: 'Slide In Elliptic Top', value: 'slide_in_elliptic_top' },
  { name: 'Slide In Elliptic Bottom', value: 'slide_in_elliptic_bottom' },
  { name: 'Slide In Elliptic Right', value: 'slide_in_elliptic_right' },
  { name: 'Slide In Elliptic Left', value: 'slide_in_elliptic_left' },
  { name: 'Bounce In Top', value: 'bounce_in_top' },
  { name: 'Bounce In Bottom', value: 'bounce_in_bottom' },
  { name: 'Bounce In Right', value: 'bounce_in_right' },
  { name: 'Bounce In Left', value: 'bounce_in_left' },
  { name: 'Roll In Top', value: 'roll_in_top' },
  { name: 'Roll In Bottom', value: 'roll_in_bottom' },
  { name: 'Roll In Right', value: 'roll_in_right' },
  { name: 'Roll In Left', value: 'roll_in_left' },
  { name: 'Roll In Blurred Top', value: 'roll_in_blurred_top' },
  { name: 'Roll In Blurred Bottom', value: 'roll_in_blurred_bottom' },
  { name: 'Roll In Blurred Right', value: 'roll_in_blurred_right' },
  { name: 'Roll In Blurred Left', value: 'roll_in_blurred_left' },
  { name: 'Swing In Top', value: 'swing_in_top' },
  { name: 'Swing In Bottom', value: 'swing_in_bottom' },
  { name: 'Swing In Right', value: 'swing_in_right' },
  { name: 'Swing In Left', value: 'swing_in_left' },
  { name: 'Fade In', value: 'fade_in' },
  { name: 'Puff In', value: 'puff_in' },
  { name: 'Flicker In', value: 'flicker_in' },
];
export const BASIC_ANNIMATIONS: Animation[] = [
  { name: 'Rotate Center', value: 'rotate_center' },
  { name: 'Rotate Top', value: 'rotate_top' },
  { name: 'Rotate Hor Center', value: 'rotate_hor_center' },
  { name: 'Rotate Ver Center', value: 'rotate_ver_center' },
  { name: 'Rotate Diagonal', value: 'rotate_diagonal' },
  { name: 'Rotate Scale', value: 'rotate_scale' },
  { name: 'Rotate Scale Down', value: 'rotate_scale_down' },
  { name: 'Rotate Scale Up Hor', value: 'rotate_scale_up_hor' },
  { name: 'Rotate Scale Down Hor', value: 'rotate_scale_down_hor' },
  { name: 'Rotate Scale Up Ver', value: 'rotate_scale_up_ver' },
  { name: 'Rotate Scale Down Ver', value: 'rotate_scale_down_ver' },
  { name: 'Rotate Scale Diag Up', value: 'rotate_scale_diag_up' },
  { name: 'Rotate Scale Diag Down', value: 'rotate_scale_diag_down' },
  { name: 'Rotate Scale Diag Up 2', value: 'rotate_scale_diag_up_2' },
  { name: 'Rotate Scale Diag Down 2', value: 'rotate_scale_diag_down_2' },
  { name: 'Flip', value: 'flip' },
  { name: 'Flip Hor Top', value: 'flip_hor_top' },
  { name: 'Flip Ver Right', value: 'flip_ver_right' },
  { name: 'Slide Top', value: 'slide_top' },
  { name: 'Slide Top Right', value: 'slide_tr' },
  { name: 'Slide Right', value: 'slide_right' },
  { name: 'Slide Bottom Right', value: 'slide_br' },
  { name: 'Slide Bottom', value: 'slide_bottom' },
  { name: 'Slide Bottom Left', value: 'slide_bl' },
  { name: 'Slide Left', value: 'slide_left' },
  { name: 'Slide Top Left', value: 'slide_tl' },
  { name: 'Slide Back In', value: 'slide_back_in' },
  { name: 'Slide Back Top', value: 'slide_back_top' },
  { name: 'Slide Back Right', value: 'slide_back_right' },
  { name: 'Slide Back Left', value: 'slide_back_left' },
  { name: 'Slide Forward Top', value: 'slide_fwd_top' },
  { name: 'Slide Forward Center', value: 'slide_fwd_center' },
  { name: 'Slide Rotate Hor Top', value: 'slide_rotate_hor_top' },
  { name: 'Slide Rotate Hot Bottom', value: 'slide_rotate_hor_bottom' },
  { name: 'Slide Rotate Right Fwd', value: 'slide_rotate_right_fwd' },
  { name: 'Slide Rotate Left Fwd', value: 'slide_rotate_left_fwd' },
  { name: 'Shadow Drop', value: 'shadow_drop' },
  { name: 'Shadow Drop Right', value: 'shadow_drop_right' },
  { name: 'Shadow Drop Left', value: 'shadow_drop_left' },
  { name: 'Shadow Drop Top', value: 'shadow_drop_top' },
  { name: 'Shadow Drop Bottom', value: 'shadow_drop_bottom' },
];
export const EXIT_ANIMATIONS: Animation[] = [
  { name: 'Scale Out Center', value: 'scale_out_center' },
  { name: 'Scale Out Horizontal', value: 'scale_out_horizontal' },
  { name: 'Scale Out Vertical', value: 'scale_out_vertical' },
  { name: 'Rotate Out Center', value: 'rotate_out_center' },
  { name: 'Rotate Out Horizontal', value: 'rotate_out_horizontal' },
  { name: 'Rotate Out Diagonal', value: 'rotate_out_diagonal' },
  { name: 'Rotate Out Fade Center', value: 'rotate_out_fade_center' },
  { name: 'Rotate Out Fade Back', value: 'rotate_out_fade_bck' },
  { name: 'Swirl Out Forward', value: 'swirl_out_fwd' },
  { name: 'Swirl Out Backward', value: 'swirl_out_bck' },
  { name: 'Flip Out Top', value: 'flip_out_top' },
  { name: 'Flip Out Bottom', value: 'flip_out_bottom' },
  { name: 'Flip Out Left', value: 'flip_out_left' },
  { name: 'Flip Out Right', value: 'flip_out_right' },
  { name: 'Flip Out Diagonal', value: 'flip_out_diagonal' },
  { name: 'Slit Out Vertical', value: 'slit_out_vertical' },
  { name: 'Slit Out Horizontal', value: 'slit_out_horizontal' },
  { name: 'Slit Out Diagonal', value: 'slit_out_diagonal' },
  { name: 'Slide Out Top', value: 'slide_out_top' },
  { name: 'Slide Out Bottom', value: 'slide_out_bottom' },
  { name: 'Slide Out Right', value: 'slide_out_right' },
  { name: 'Slide Out Left', value: 'slide_out_left' },
  { name: 'Slide Out Back', value: 'slide_out_back' },
  { name: 'Slide Out Forward', value: 'slide_out_forward' },
  { name: 'Slide Out Blurred Top', value: 'slide_out_blurred_top' },
  { name: 'Slide Out Blurred Bottom', value: 'slide_out_blurred_bottom' },
  { name: 'Slide Out Blurred Right', value: 'slide_out_blurred_right' },
  { name: 'Slide Out Blurred Left', value: 'slide_out_blurred_left' },
  { name: 'Slide Out Elliptic Top', value: 'slide_out_elliptic_top' },
  { name: 'Slide Out Elliptic Bottom', value: 'slide_out_elliptic_bottom' },
  { name: 'Slide Out Elliptic Right', value: 'slide_out_elliptic_right' },
  { name: 'Slide Out Elliptic Left', value: 'slide_out_elliptic_left' },
  { name: 'Slide Out Bounce Out Top', value: 'slide_out_bounce_out_top' },
  { name: 'Slide Out Bounce Out Bottom', value: 'slide_out_bounce_out_bottom' },
  { name: 'Slide Out Bounce Out Right', value: 'slide_out_bounce_out_right' },
  { name: 'Slide Out Bounce Out Left', value: 'slide_out_bounce_out_left' },
  { name: 'Roll Out Top', value: 'roll_out_top' },
  { name: 'Roll Out Bottom', value: 'roll_out_bottom' },
  { name: 'Roll Out Left', value: 'roll_out_left' },
  { name: 'Roll Out Top', value: 'roll_out_top' },
  { name: 'Roll Out Right', value: 'roll_out_right' },
  { name: 'Roll Out Blurred Top', value: 'roll_out_blurred_top' },
  { name: 'Roll Out Blurred Bottom', value: 'roll_out_blurred_bottom' },
  { name: 'Roll Out Blurred Right', value: 'roll_out_blurred_right' },
  { name: 'Roll Out Blurred Left', value: 'roll_out_blurred_left' },
  { name: 'Swing Out Top', value: 'swing_out_top' },
  { name: 'Swing Out Bottom', value: 'swing_out_bottom' },
  { name: 'Swing Out Left', value: 'swing_out_left' },
  { name: 'Swing Out Right', value: 'swing_out_right' },
  { name: 'Fade Out', value: 'fade_out' },
  { name: 'Fade Out Back', value: 'fade_out_back' },
  { name: 'Fade Out Top', value: 'fade_out_top' },
  { name: 'Fade Out Bottom', value: 'fade_out_bottom' },
  { name: 'Fade Out Left', value: 'fade_out_left' },
  { name: 'Fade Out Right', value: 'fade_out_right' },
  { name: 'Puff Out Center', value: 'puff_out_center' },
  { name: 'Puff Out Top', value: 'puff_out_top' },
  { name: 'Puff Out Bottom', value: 'puff_out_bottom' },
  { name: 'Puff Out Left', value: 'puff_out_left' },
  { name: 'Puff Out Right', value: 'puff_out_right' },
  { name: 'Flicker Out', value: 'flicker_out' },
];
export const TEXT_ANIMATIONS: Animation[] = [
  { name: 'Tracking In Expand', value: 'tracking_in_expand' },
  { name: 'Tracking In Exapnd Forward', value: 'tracking_in_expand_fwd' },
  { name: 'Tracking In Expand Fwd Top', value: 'tracking_in_expand_fwd_top' },
  { name: 'Tracking In Expand Fwd Bottom', value: 'tracking_in_expand_fwd_bottom' },
  { name: 'Tracking In Contract', value: 'tracking_in_contract' },
  { name: 'Tracking In Contract Back Top', value: 'tracking_in_contract_back_top' },
  { name: 'Tracking In Contract Back Bottom', value: 'tracking_in_contract_back_bottom' },
  { name: 'Text In Focus', value: 'text_focus_in' },
  { name: 'Text In Focus Expand', value: 'text_focus_in_expand' },
  { name: 'Text In Focus Contract', value: 'text_focus_in_contract' },
  { name: 'Text Flicker In', value: 'text_flicker_in' },
  { name: 'Tracking Out Contract', value: 'tracking_out_contract' },
  { name: 'Tracking Out Contract Top', value: 'tracking_out_contract_top' },
  { name: 'Tracking Out Contract Bottom', value: 'tracking_out_contract_bottom' },
  { name: 'Tracking Out Expand', value: 'tracking_out_expand' },
  { name: 'Tracking Out Expand Forward Top', value: 'tracking_out_expand_fwd_top' },
  { name: 'Tracking Out Expand Forward Bottom', value: 'tracking_out_expand_fwd_bottom' },
  { name: 'Text Blur Out', value: 'text_blur_out' },
  { name: 'Text Blur Out Expand', value: 'text_blur_out_expand' },
  { name: 'Text Blur Out Contract', value: 'text_blur_out_contract' },
  { name: 'Text Flicker Out', value: 'text_flicker_out' },
  { name: 'Text Pop Up Top', value: 'text_pop_up_top' },
];
